### ISSUE TITLE
Creating channel file not found

### ISSUE THREAD

**Issue by marcosrachid** [aidtechnology/hgf-k8s-workshop#19]
When trying to run the following command:
`kubectl exec -n peers $PEER_POD -- peer channel create -o ord1-hlf-ord.orderers.svc.cluster.local:7050 -c mychannel -f /hl_config/channel/mychannel.tx`

I'm getting the return:

> 2019-07-26 20:31:21.144 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
> Error: channel create configuration tx file not found open /hl_config/channel/mychannel.tx: no such file or directory
> command terminated with exit code 1

Is anything wrong with my interpretation ?

**Comment by dgurindapalli** [comment]
While installing Peer please use the below command, Basically we need to set channels

helm install stable/hlf-peer -n peer1 --namespace peers -f ../helm_values/peer1.yaml --set secrets.channels[0]=hlf--channel

**Comment by mohammedrampurawala1111** [comment]
@marcosrachid the error tells that file does not exists in  /hl_config/channel directory so check secrets are configured properly or you can try copying mychannel.tx file manually into that directory.

**Comment by marcosrachid** [comment]
I resolved it with @Privet-mir solution, didn't try setting on helm install.

**Comment by mr-rooftop** [comment]
Hi guys!
I have exactly the same problem as @marcosrachid while trying to replicate the official slides (https://schd.ws/hosted_files/hgf18/d2/2018_12_14_CH_Basel_Hyperledger_Global_Forum.pdf).

I use fabric-samples 1.4.3, helm charts versions 1.4.3 and Kubernetes version 1.15.5 on client and server.

Bashing into the peer, making the directories /hl_config/channel/ with mkdir and then copying mychannel.tx file manually into /hl_config/channel/ works. 
After that I can execute 
`kubectl exec -n peers $PEER_POD -- peer channel create -o ord1-hlf-ord.orderers.svc.cluster.local:7050 -c mychannel -f /hl_config/channel/mychannel.tx`

However, after that, I want to to execute the next command to join the channel:
`kubectl exec -n peers $PEER_POD -- peer channel fetch config/var/hyperledger/mychannel.block -c mychannel -o ord1-hlf-ord.orderers.svc.cluster.local:7050`

and this throws me 
`Endorser and orderer connections initialized
Error: fetch target illegal: config/var/hyperledger/mychannel.block
command terminated with exit code 1`

Which means the the output of the channel create command, the mychannel.block file, was never put in config/var/hyperledger/.
Btw, this file path also doesn't exist.
How does it come, that these file paths /hl_config/channel/ and config/var/hyperledger/ don't exist, and that the mychannel genesis files are never copied there?

**Comment by mr-rooftop** [comment]
Update:
In the line 
`kubectl exec -n peers $PEER_POD -- peer channel fetch config/var/hyperledger/mychannel.block -c mychannel -o ord1-hlf-ord.orderers.svc.cluster.local:7050`
I mistakenly forgot a space character between config and /var/hyperledger/mychannel.block.
After this change, the procedure with manually copying mychannel.tx into /hl_config/channel/ via kubectl cp worked!

**Comment by mr-rooftop** [comment]
Update2
I got everything to work as expected like this:

When the guys from AID:Tech enabled multi-channel support in the hlf-peer helm chart (https://github.com/helm/charts/commit/d58c7d46a08b040ef8ff87f83dc67911ce98f1bb#diff-94c989ac8c447eb60ea9486bfd2822c4), they just didn't update the README in this repo. 

Now, the channel secret in the peer1.yaml must be given in some kind of array form, instead of one single channel

In the peer1.yaml file in the helm_values folder, change 
`channel: hlf--channel`
to e.g.
`channels:
  mychannel.tx: hlf--channel`

By making this change and installing the peer chart with these values, the mychannel.tx file is finally copied to the /hl_config/channel/hlf--channel/  directory. 

Because this is a different directory than in the original tutorial, you also need to change the command

`kubectl exec -n peers $PEER_POD -- peer channel create -o ord1-hlf-ord.orderers.svc.cluster.local:7050 -c mychannel -f /hl_config/channel/mychannel.tx`

to use the right directory like so

`kubectl exec -n peers $PEER_POD -- peer channel create -o ord1-hlf-ord.orderers.svc.cluster.local:7050 -c mychannel -f /hl_config/channel/hlf--channel/mychannel.tx`

This way the peer channel create command can access the mychannel.tx for creating the mychannel.block file in the orderer container.

I hope that helps someone else who's struggling!

**Comment by chebyte** [comment]
@mr-rooftop this fix works fine thanks, but now I get this error
````
kubectl exec -n peers $PEER_POD -- peer channel create -o ord1-hlf-ord.orderers.svc.cluster.local:7050 -c mychannel -f /hl_config/channel/hlf--channel/mychannel.tx
2020-06-18 21:33:06.196 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
Error: got unexpected status: FORBIDDEN -- Failed to reach implicit threshold of 1 sub-policies, required 1 remaining: permission denied
command terminated with exit code 1
````
maybe when I created the genesis block was missing the channelId params in the presentations, so I added mychannel, maybe this is the problem?

````
configtxgen -profile OrdererGenesis -channelID mychannel -outputBlock ./genesis.block
````
